### ISSUE TITLE
Download data.zip

### ISSUE THREAD

**Issue by mengqing0312** [MPForte/SGNify#13]
I want to test this excellent job on my own video, but I found that the link to download data.zip'https://download.is.tue.mpg.de/download.php?domain=sgnify&sfile=data.zip&resume=1' seems to be invalid. 
May I know when it will open? Thank you very much.

**Comment by MPForte** [comment]
Once you register on the website, there are three links available:
List with the signs: https://download.is.tue.mpg.de/download.php?domain=sgnify&resume=1&sfile=signs.txt
Frames: https://download.is.tue.mpg.de/download.php?domain=sgnify&resume=1&sfile=frames.zip
Ground-truth SMPL-X Fits: https://download.is.tue.mpg.de/download.php?domain=sgnify&resume=1&sfile=smplx_gt.zip

**Comment by MPForte** [comment]
I updated `install.sh`.
It should work now, please let me know if it does not!
