### ISSUE TITLE
Demo can not run！

### ISSUE THREAD

**Issue by herochen7372** [MPForte/SGNify#16]
Hi,can you help me for this error?
![图片](https://github.com/MPForte/SGNify/assets/97960617/90eaf142-aff6-4b92-816e-e60966926002)

**Comment by herochen7372** [comment]
And I can't find the package of  'vitpose'.

from vitpose.utils.inference import vitpose_inference_model
from vitpose.utils.visualization import draw_points_and_skeleton, joints_dict

**Comment by mhannani** [comment]
Hello @herochen7372, Did it work for you already? Seems something missing in the source code

**Comment by mhannani** [comment]
pip git+https://github.com/nghorbani/ViTPose
