### ISSUE TITLE
How to get vertex ids of upperbody?

### ISSUE THREAD

**Issue by 2000ZRL** [MPForte/SGNify#17]
Dear authors,

I am trying to evaluate the model. I can get hand ids, but how to get upper body vertex ids?

**Comment by MPForte** [comment]
Please refer to this file:

[smplx_vert_segmentation.json](https://github.com/user-attachments/files/17602694/smplx_vert_segmentation.json).

For the hands only, you can also use `MANO_SMPLX_vertex_ids.pkl` and the keys: 'left_hand' and 'right_hand'
