### ISSUE TITLE
Slow testing on 5 second video processing takes over an hour with A5000 GPU.

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#2]
Is it possible to not render the mesh, or do something else to make the process faster?

**Comment by MPForte** [comment]
SGNIfy is an optimization method, so it is unfortunately way slower than regression methods.
Furthermore, we need to preprocess the data to get the best possible hand pose.
This makes the full method very slow.
If the hand pose for the sign is given in advance, this would make the code at least 50% faster.
Another option is to disable the contact loss, computing the winding numbers takes lots of time (this would make the process approximately 30% faster)
