### ISSUE TITLE
Interpolate.py file does not exist

### ISSUE THREAD

**Issue by AIMads** [MPForte/SGNify#5]
Hey Sorry for posting all the issues, really excited about your work and I badly want to test it out, so testing every detail ;) 

Tried to test it on a video containing a SL sentence, but got an error as an attempt towards interpolation was made, but the interpolation file does not exist.

Error log:
python: can't open file '/home/humaid/Desktop/SGNify/SGNify/smplifyx/interpolate.py': [Errno 2] No such file or directory
Finding sign class...
2b
Finding the RPS using valid MediaPipe frames...
Interpolating right hand...
Traceback (most recent call last):
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 482, in <module>
    main(args)
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 414, in main
    compute_rps(
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 178, in compute_rps
    interpolate(
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 201, in interpolate
    return run(
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'SGNify/smplifyx/interpolate.py', '--pkl', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_1.pkl'), PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_2.pkl'), '--save_folder', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/interp_right'), '--config', 'SGNify/cfg_files/fit_smplifyx_ref_sv.yaml', '--reference_start', '20', '--reference_end', '275', '--end_frame', '312']' returned non-zero exit status 2.

**Comment by athenas-lab** [comment]
interpolate.py is in the utils folder, not in smplifyx.

you will need to change the call to interpolate() in utils/rps.py as follows:
`
def interpolate(*, pkl_1, pkl_2, save_folder, reference_start, reference_end, end_frame):
    return run(
        [
            "python",
            "utils/interpolate.py",
            "--pkl",
            pkl_1,
            pkl_2,
            "--save_folder",
            save_folder,
            "--config",
            "cfg_files/fit_smplifyx_ref_sv.yaml",
            "--reference_start",
            str(reference_start),
            "--reference_end",
            str(reference_end),
            "--end_frame",
            str(end_frame),
        ],
        check=True,
    )
`

**Comment by AIMads** [comment]
Amazing thank you! I will test it out 🙏

**Comment by MPForte** [comment]
Updated it in the code as well!
