### ISSUE TITLE
Deployment on Colab version 20230622

### ISSUE THREAD

**Issue by SlimeVRX** [MPForte/SGNify#6]
Thanks to the author's work!

I just deployed to run [Colab](https://colab.research.google.com/drive/1GU4Fa9IMLDNmF4hsBn-sZvGCEqCz7z1P?usp=sharing) version 20230622

**Comment by SlimeVRX** [comment]
39 Frames processed in 135 minutes on GPU T4 Colab

**Comment by SlimeVRX** [comment]
Sorry to the Author because I used the drive link to download `data.zip` instead of the https://download.is.tue.mpg.de/download.php link. I will fix it after testing is done.

**Comment by MPForte** [comment]
Thank you for creating the colab version!
