### ISSUE TITLE
Request for dataset download script

### ISSUE THREAD

**Issue by Wei-Chen-hub** [MPForte/SGNify#7]
Hi, i am very interested in the dataset provided along with SGNify.

However I only download "sign.txt" from the download link in homepage, other two seem not link to valid file. Could you please kindly provide a download script. That would be very helpful for accessing the dataset.

Thank you very much!

**Comment by MPForte** [comment]
Hello,
We updated the structure of the dataset to allow users to download the data quickly.
Try again now!

**Comment by Wei-Chen-hub** [comment]
Thank for your update!
And sorry for raising this issue again, but seems that download link for SMPL-X fitting is still not included?

**Comment by MPForte** [comment]
We uploaded the new folders with the ground-truth SMPL-X fittings!
