### ISSUE TITLE
Some fixes for errors when running sgnify.py

### ISSUE THREAD

**Issue by athenas-lab** [MPForte/SGNify#8]
First, during installing the env, the environment.yml file specifies pyrender==0.1.23 under conda and networkx==2.5.1 under pip. This resulted in some incompatibilities for me due pyglet. So I had to move pyrender to the pip section and removed the versions for pyrender and networkx. This will install the latest versions (installed networkx-3.1 pyglet-2.0.8 pyrender-0.1.45) and this worked.

I also encountered several errors when running the different steps in sgnify.py and here are the fixes that worked for me.  Just thought it may help others who encounter these errors.

1) if you get interpolate.py not found in Step 4:

interpolate.py is in the utils folder, not in smplifyx.

you will need to change the call to interpolate() in utils/rps.py as follows:
`
def interpolate(*, pkl_1, pkl_2, save_folder, reference_start, reference_end, end_frame): return run( [ "python", "utils/interpolate.py", "--pkl", pkl_1, pkl_2, "--save_folder", save_folder, "--config", "cfg_files/fit_smplifyx_ref_sv.yaml", "--reference_start", str(reference_start), "--reference_end", str(reference_end), "--end_frame", str(end_frame), ], check=True, )
`

2) if you get rotation_conversion not found:
In utils/interpolate.py there is a line 
`
import rotation_conversion
`
Change this to the following and make sure pytorch3d is installed.
`
import pytorch3d.transforms.rotation_conversions as rotation_conversion
`

3) if you get cmd_parser nor found:
Make the following change to utils/interpolate.py
`
import sys
sys.path.append("smplifyx")
from cmd_parser import parse_config
`

4) When running SPECTRE (step 6), I encountered a few errors in the mobilenetv2 and resnet50 models, since old models were being used by default. To fix these errors, change the path to the updated models as follows.
For mobilenetv2, make the following change in spectre/src/models/encoders.py: 
   The following is the original code. Comment this out, since it uses an older model.
       `self.encoder = torch.hub.load('pytorch/vision:v0.8.1', 'mobilenet_v2', pretrained=True) `
   instead change the code as follows.
       `self.encoder = torch.hub.load('pytorch/vision', 'mobilenet_v2', pretrained=True) `
           
For resnet50, download the Resnet50_Final.pth model from
https://drive.google.com/drive/folders/1oZRSG0ZegbVkVwUd8wUIQx8W7yfZ_ki1
and point to the downloaded file in spectre/external/face_detection/ibug/face_detection/retina_face/retina_face_predictor.py in the following function.

    def get_model(name: str = 'resnet50') -> SimpleNamespace:
        name = name.lower().strip()
        if name == 'resnet50':
            return SimpleNamespace(weights=<DOWNLOADED_DIR>/'Resnet50_Final.pth'),
                                   config=SimpleNamespace(**deepcopy(cfg_re50)))

**Comment by AIMads** [comment]
Tried your changes, but got the following error:

Interpolating right hand...
Traceback (most recent call last):
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 482, in <module>
    required=False,
  File "/home/humaid/Desktop/SGNify/sgnify.py", line 414, in main
    print(args.sign_class)
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 178, in compute_rps
    interpolate(
  File "/home/humaid/Desktop/SGNify/utils/rps.py", line 200, in interpolate
    return run([ "python", "utils/interpolate.py", "--pkl", pkl_1, pkl_2, "--save_folder", save_folder, "--config", "cfg_files/fit_smplifyx_ref_sv.yaml", "--reference_start", str(reference_start), "--reference_end", str(reference_end), "--end_frame", str(end_frame), ], check=True, )
  File "/home/humaid/mambaforge/envs/sgnify/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'utils/interpolate.py', '--pkl', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_1.pkl'), PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/ref_right_2.pkl'), '--save_folder', PosixPath('/home/humaid/Desktop/SGNify/output/s_5440/.tmp/rps/interp_right'), '--config', 'cfg_files/fit_smplifyx_ref_sv.yaml', '--reference_start', '20', '--reference_end', '275', '--end_frame', '312']' returned non-zero exit status 1.
